baseURL = 'https://getclever.marketing/'
languageCode = 'en-us'
title = 'Clever Marketing, Ltd.'
enableGitInfo = true

[sass]
  use_dart_sass = true

# upload_dir = "assets/uploads"
# public_path = "/uploads"
# disableKinds = [ "taxonomy", "term" ]

[taxonomies]
  category  = "categories"     # for blog/Insights
  industry = "industries"    # for Projects

[permalinks]
  categories = "/insights/categories/:slug/"
  industries = "/portfolio/industries/:slug/"

[pagination]
  pagerSize = 9


# config.toml
[outputs]
home     = ["HTML"]      # no /index.xml on homepage
section  = ["HTML"]      # no /<section>/index.xml
taxonomy = ["HTML"]      # no /<taxonomy>/index.xml
term     = ["HTML"]      # no /<taxonomy>/<term>/index.xml


[params]
  twic = "clvrmktg"
  share = "/fallbacks/clvr-cover.jpg"
  logo = "/logo.png"

  # Homepage Title | Tagline
  tagline = 'Bahamas Web Design | Nassau, Bahamas'

[params.google]
  api_key = "AIzaSyDGa9bRzCbbmJ-L9PIX1hrZSymdSC4ZEtA"
  place_id = "ChIJpwI7ux9nL4kRn7lrM-ie_dk"
  app_id = 9879175018863603
  # 384650276688740
  error = true


[params.social]
  facebook = "clvrmktg"
  instagram = "clvrmktg"
  linkedin = "clvrmktg"
  x = "clvrmktg"
  whatsapp = "+1 (242) 376-3340"
  linkedinType = "company" # or "in" for personal profile URLs

[[menu.main]]
  identifier = "services"
  name = "Services"
  url = "/bahamas-web-design-services/"
  weight = 1

[[menu.main]]
  parent = "services"
  name = "Web Design"
  url = "/bahamas-web-design-services/website-design-bahamas/"
  weight = 1

[[menu.main]]
  parent = "services"
  name = "Search Engine Optimization"
  url = "/bahamas-web-design-services/seo-bahamas/"
  weight = 2

[[menu.main]]
  parent = "services"
  name = "Digital Marketing"
  url = "/bahamas-web-design-services/digital-marketing-bahamas/"
  weight = 3

[[menu.main]]
  parent = "services"
  name = "Website Maintenance"
  url = "/bahamas-web-design-services/website-maintenance/"
  weight = 4

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  url = "/portfolio/"
  weight = 2

[[menu.main]]
  identifier = "about-us"
  name = "About Us"
  url = "/about-us/"
  weight = 3

# [[menu.main]]
#   identifier = "insights"
#   name = "Insights"
#   url = "/insights/"
#   weight = 4

[[menu.main]]
  identifier = "contact-us"
  name = "Contact Us"
  url = "/contact-us/"
  weight = 4


[[menu.policies]]
  identifier = "privacy-policy"
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 1

[[menu.policies]]
  identifier = "terms-service"
  name = "Terms of Service"
  url = "/terms-service/"
  weight = 2

[[menu.policies]]
  identifier = "cookie-policy"
  name = "Cookie Policy"
  url = "/cookie-policy/"
  weight = 3

[[menu.policies]]
  identifier = "accessibility-statement"
  name = "Accessibility Statement"
  url = "/accessibility-statement/"
  weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

    # Links
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        enableDefault = true
        
[security.funcs]
getenv = ['^HUGO_', '^GA_TRACKING_ID$']


[sitemap]
  filename = "sitemap.xml"
  changefreq = "monthly"
  priority = 0.5
