[build]
publish = "public"
command = """
set -euo pipefail

: "${DART_SASS_VERSION:=1.83.4}"

# Download to a known name (don't use -J)
curl -fsSL "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" -o dart-sass.tgz

# Extract & clean up
tar -xzf dart-sass.tgz
rm dart-sass.tgz

# Use repo path so it works regardless of CWD
export PATH="$(pwd)/dart-sass:$PATH"

hugo --gc --minify
"""

[build.environment]
  HUGO_VERSION = "0.142.0"
  HUGO_ENV = "production"
  DART_SASS_VERSION = "1.83.4"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "22"  # Ensure only one version is defined
  GO_VERSION = "1.23.5"
  TZ = "America/New_York"

[context.production.environment]
  HUGO_VERSION = "0.142.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.142.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.142.0"

[dev]
  command = "hugo server"
  port = 8888
  targetPort = 1313

[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301
  force = true

